---
title: "Grading guide"
author: "Marius Swane Wishman"
output: pdf_document
---

Part 1
======

Question 1
----------

The candidate should explain the three social classes in Ricardo's view, and
that landowners are a drain on the economy at the cost of the other classes.
Specifically the candidate should explain and model how when the economy expands
more land is put to use the productivity of that land declines (assumption of
marginal productivity of land). While the capitalist of the new land earns less
profit due to the fall in productivity, he still has to pay rent. While he pays
less rent than for more valuable land, it nevertheless puts upward pressure on
the value of land (and thus rents) in the market (assuming competition). Thus
rents take an increasing share of the value created, at the cost of profits
(which in the classical economic tradition is synonymous with economic growth).
It is key that the candidate explains this reasoning, and not just what 'happens
in the model'. Wages are assumed to be constant at subsistence level.

Question 2
----------

The candidate should draw a model of a supply shift, and **explain why** price
and quantity demanded are affected the way they are. The candidate should also
justify why the model assumes constant supply (marginal analysis). The candidate
should also at least one example of things that could cause shifts in demand.

Question 3
----------

The candidate should explain comparative advantages relative to absolute
advantages, provide calculations (more or less exact) of the respective
opportunity costs and explain what that means. Using the opportunity costs the
candidate should demonstrate how both parties can be better off by trading,
giving the range of mutual beneficial trades. The candidate should conclude that
Italy has an absolute advantage in both good, but a comparative advantage in
wine (and Greece in olives). The candidate should show awareness of how the
assumption of frictionless trade (no trade barriers or transportation costs)
affect the conclusion.

Question 4
----------

The candidate should present Marx equation of rate of profits, and explain how
when capitalists (in an effort to increase profits) increase the portion of
constant capital in the organic composition of capital, it actually decreases
the **rate** of profit. This makes industry ever more capital intensive as
bigger and bigger investments are needed to make a profit. This does not mean
that capitalists will stop investing. They will not because they lack any
central authority, and any one capitalist disengaging will loose out. The ever
larger investments do however increase the risk of failure and economic crises.
They also put an increasing pressure on capitalist to increase the rate of
exploitation as an alternative route to profit, however this leads to increased
risk of underconsumption.

Question 5
----------

The candidate only needs to know that this is *individual* firms and consumers.

Question 6
----------

The candidate should show awareness that pre-industrial economies largely
consists of farmers who typically do not own any land. The candidate should then
explain how land reform makes the most of the cheap labor that is available in
the economy, and how multiple individual farming enterprises creates conditions
very similar to the assumptions of the neo-classical tradition (with farmers now
incentivised to maximize their effort to obtain profits) and how 'gardening'
allows maximizing labor input to increase yields in the lack of capital. The
candidate should explain how the profits generated by farming creates a domestic
market for easy-to-produce manufactured goods, thus setting the economy up for
"the next step".

Question 7
----------

Because no candidates got this question quite right, it will only count positively
toward grading.

Part 2
======

Regardless of which question the candidate chooses he/she is expected to produce
a well **structured** text that above all relies on **theoretical
argumentation** toward a conclusion or answer to the chosen question.
