---
title: "Classical PE notes"
output: pdf_document
---

Historical Context - The Emergence of Capitalism
------------------------------------------------

- Expansion of trade (colonies, inventions in banking, limited liability)
- Improvements in production & agriculture
- Population growth & concentration
- Revolutions
- Chicken or the egg? Capitalism or technological innovation?

Adam Smith 1723-90
------------------

- The founder of Economics or at least political economy (wealth of nations)
- The invisible hand (DO NOT OVER STATE THIS!)
- Greed is good, it tends to self-structure
- Mercantilism and "Just prices"
- It's about MOTIVATION -> increased efforts
- COMPETITION (EXAMPLE - airports)
	- He even noted that if left to themselves people of the same trade will 
	  collude to rig prices
	- AKA need for regulation
	- Provision of public goods
- Division of labor - Pin factory -> Fordism

What is the theory?
-------------------

- Conclusion: Individual rational pursuit of self interest can be a public good
- Theory: "greed" -> competition & specialization -> increased economic output

When actors are allowed to compete in a market, provision of goods and services
improve over time

Works through COMPETITION, in the age of mercantilism this
meant a need for less government interference ... But today?

David Ricardo 1772-1823
-----------------------

- Comparative advantage, but not only that
- THE classical theory of international trade
- Has not aged like Smith
- The benefits of international (free) trade
- Absolute advantage 
	- Bananas vs potatoes, Norway and Costa Rica (Smith)
	This is when trade happens according to Smith
	Both have more stuff

- Comparative advantage 	
	- Was the above example of comparative? Yes
	- Pairwise, two parties (countries) and tow products
	- You can have absolute advantage in both, but still benefit from
	  exchange!
	- What you are the most better at!

- Practice!

- Class -- a product of source of income, competing interests
- The interaction between rent, capital and labor
- More on this in the seminar
- Reinert: Ricardo is wrong!

Thomas Malthus 1766-1823
------------------------

- Draw Malthusian growth **model**
- What happened? He was wrong!

....Or? Let's not forget that he described all of human history up until that
point (in one graph/model)

Jean-Babtiste Say 1767-1832
---------------------------

- Say's Law 
- If you want to buy something (demand) you have to produce something 
  (increasing supply) in order to exchange

	If and you would not produce anything for the sake of just keeping it 
	(u don't need thousands of beers, or at least u need other stuff for
	your party as well)

	Thus when u produce one more potato than u need, you want to exchange it
	for something else (increasing demand)
	
- Overproduction in one part of the economy would be matched by underproduction 
  elsewhere, prices would correct the market
- Notice that this is a "Law", it was held to be True, until later in the course.

There are others in Stillwell, they are also relevant, and we'll get to know at least one of them in the seminar

John Stewart Mill (1806-73) 
----------------------------

- The great synthesizer!
- Used as *the* book on economics (PE) until the neo-classicals we will
  encounter next week
- Tempered faith in markets. Worried about inequality and environmental
  degradation (proffering the stationary state).

Summary discussion
------------------

- To what degree were the classical political economists pro laissez-faire? What
  where their counter points to free markets?
  	- Discussed in terms of moral short comings, to be addressed by politics
