#+title: Committee Comments
#+author: Marius Swane Wishman

* Conceaptualization/Terminology
** Historical/pre-colonial
*** "Much" colonization before 1800

* "Theoretical contribution of the thesis consists mainly a collection of different mechanisms with (sometimes) different assumptions behind them."
** Lacking "overarching theoretical framework"

* "Not clear why" the mechanisms outlined in OMT only apply to non-state actors
** Far away high SP should also be better at bargaining (internal reduction of violence only matters for this paper)
*** Earlier drafts were more focused on testing existing theory went more into this (because of Tore's paper)
*** I agree, but empirically this effect seems to be "overpowered".

* Introduction should have outlined "what might be resonable implications of this work"

* What is the distance measure really capturing?
** Compare high SP close to capital, to pre-colonial state capital ovelaps current capital
*** In other words to test the degree to which the measure proxies what i assume (hope) it proxies
*** Of course, this will not always be the case, and in some cases it may be true, but the ethnic group tied to the pre-colonial state may be excluded from power, but such is the nature of proxies
*** I made some attempts at this, and similar things, but I could not figure out the coding. However, it should be doable and is definetly a next step


* "It seems implasible to assume that being 100km away from the capital should matter more than say, being 500km away, if both groups are excluded from power."
** It matters because it affects the relative military capabilities of the state and those groups. Halvar paper.

* Clarify the necessary assumptions to drawing "causal" conclusions

* Endodegneity of HSE -> configuration of present states and capitals -> conflict
** Historical conflict?

* Substantive importancse of correlations compared to other effects?
** Tempting, but dangerous

* Qualitative/mixed methid is lacking
** Yes, but we did read quite a lot of case studies the like. Some of it is referenced, but a lot of it informed the study in more indirect ways.

* ARC paper does not fit
** limited contribution? Push back carefully
** Incentives to include:
*** I did a lot of work on it, and expluding it would feel a bit wasteful.
*** Purposefully vague guidelines conserning how much work the thesis shold contain
** Incentives to exclude:
** Working on the ARC data made me revise my initial ideas and led me down this path
*** Initial path was Alesina et.al.'s measure of boundry squigglyness, concluded that African borders are actually not as bad as one would think (in this regard), and that old states mattered more for organizations and the artificiallity of states.

* More info on institutions
** I wish I had this.. Difficult to do poorly, impossible to do well

* More info on which HSE institutions still exist
** Again, I wish I had it...
** This is a whole separate data project..
** The *proxy* of distance to capital was the best I could come up with. I am open to suggestions! :)
